### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by clytaemnestra** [pyvec/cz.pycon.org#2]
Potřebujeme vyřešit nasazení do beta a následně do produkčního prostředí, které běží v rosti.cz. Máme dvě instance k dispozici, beta na testování a produkční, a k nim se připojujeme pomocí SSH klíčů.

Ve starém repu jsme používali knihovnu Fabric na nasazení. [Tady](https://github.com/pyvec/pycon/pull/1) je work in progress MR - nahrála jsem deployment klíče, nicméně z nějakého důvodu to pořád nefunguje - vrací mi to chybu `invalid key`. 

Chtěli bychom také použít Gunicorn a spouštět to z Dockeru. 

Potřebovali bychom oba typy nasazení: 
* automatické přes nějakou pipelinu 
* manualní by bylo supr, kdyby šlo, ale nemusí být.

Přístupy na všechny prostředí a repo mám já. 

Můžeme použít jakoukoliv knihovnu nebo cokoliv na nasazení. Jediné omezení je, používáme rosti.cz, protože to tam běží léta a máme to zdarma.

**Comment by starenka** [comment]
btw jak koukam, tak v tom adresari je ale stejne vycekautovany upe jiny repo....

```(venv) app@pycon_beta_2174 ~/app $ cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/pyvec/cz.pycon.org-2019.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "beta"]
	remote = origin
	merge = refs/heads/beta
```

**Comment by clytaemnestra** [comment]
Už vyřešeno, použijeme fly.io.
